#!/bin/bash

module load gcc/7.3.0
module load mkl

export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:/usr/local/intel/15.0.1.133/composer_xe_2015.1.133/mkl/lib/intel64

ITENSORDIR='/home/herbjace/Scratch/iTensor/itensor_single'
MKLDIRL='/usr/local/intel/15.0.1.133/composer_xe_2015.1.133/mkl/lib/intel64/'
MKLDIRI='/usr/local/intel/15.0.1.133/composer_xe_2015.1.133/mkl/include/'

g++ main.cpp -o job -m64 -std=c++17 -fconcepts -fPIC -I${ITENSORDIR} -O2 -DNDEBUG -Wall -Wno-unknown-pragmas -Wno-unused-variable -L${ITENSORDIR}/lib -litensor -lmkl_intel_lp64 -lmkl_sequential -lmkl_rt -lmkl_core -lpthread -I${MKLDIRI} -L${MKLDIRL}
