#!/bin/bash

g++ main.cpp -o kondo_heisenberg_model -m64 -std=c++17 -fconcepts -fPIC -I '/home/maciej/itensor' -O2 -DNDEBUG -Wall -Wno-unknown-pragmas -Wno-unused-variable -L'/home/maciej/itensor/lib' -litensor -larmadillo -lpthread -L/usr/lib -lblas -llapack

