#!/bin/bash

qsub -v L='4',cutoff='1E-6' -N L4E6 run_stress_test
qsub -v L='8',cutoff='1E-6' -N L8E6 run_stress_test
qsub -v L='12',cutoff='1E-6' -N L12E6 run_stress_test
qsub -v L='16',cutoff='1E-6' -N L16E6 run_stress_test
qsub -v L='20',cutoff='1E-6' -N L20E6 run_stress_test
qsub -v L='24',cutoff='1E-6' -N L24E6 run_stress_test
qsub -v L='28',cutoff='1E-6' -N L28E6 run_stress_test
qsub -v L='32',cutoff='1E-6' -N L32E6 run_stress_test
qsub -v L='36',cutoff='1E-6' -N L36E6 run_stress_test
qsub -v L='40',cutoff='1E-6' -N L40E6 run_stress_test
qsub -v L='44',cutoff='1E-6' -N L44E6 run_stress_test
qsub -v L='48',cutoff='1E-6' -N L48E6 run_stress_test

qsub -v L='4',cutoff='1E-8' -N L4E8 run_stress_test
qsub -v L='8',cutoff='1E-8' -N L8E8 run_stress_test
qsub -v L='12',cutoff='1E-8' -N L12E8 run_stress_test
qsub -v L='16',cutoff='1E-8' -N L16E8 run_stress_test
qsub -v L='20',cutoff='1E-8' -N L20E8 run_stress_test
qsub -v L='24',cutoff='1E-8' -N L24E8 run_stress_test
qsub -v L='28',cutoff='1E-8' -N L28E8 run_stress_test
qsub -v L='32',cutoff='1E-8' -N L32E8 run_stress_test
qsub -v L='36',cutoff='1E-8' -N L36E8 run_stress_test
qsub -v L='40',cutoff='1E-8' -N L40E8 run_stress_test
qsub -v L='44',cutoff='1E-8' -N L44E8 run_stress_test
qsub -v L='48',cutoff='1E-8' -N L48E8 run_stress_test


